At the core of the NumPy package, is the **ndarray** object. This encapsulates n-dimensional arrays of homogeneous data types,

**important differences between NumPy arrays and the standard Python sequences:**


1.   NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
2.   The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements

-->vectorized code is more concise and easier to read





In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)


print(arr.ndim)  # Output: 2 (since it's a 2D array)

print(arr.dtype)  # Output: int64 (or int32 depending on your system)

arr_float = np.array([1.2, 2.3, 3.4], dtype=np.float32)
print(arr_float.dtype)  # Output: float32

print(arr.size)  # Output: 6 (because there are 6 elements in the array)

arr = np.array([1, 2, 3, 4])
arr2 = arr * 2  # All elements are multiplied by 2
print(arr2)  # Output: [2, 4, 6, 8]

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing an element
print(arr[0, 1])  # Output: 2

# Slicing a row
print(arr[1, :])  # Output: [4, 5, 6]

# Modifying a value
arr[0, 0] = 10
print(arr)  # Output: [[10, 2, 3], [4, 5, 6]]


ndim: Number of dimensions (axes).

shape: Tuple showing the size along each dimension.

dtype: Data type of the elements.

size: Total number of elements.

itemsize: Size in bytes of each element.

data: The actual buffer containing the array’s data (rarely used directly).

np.arange() is a function in NumPy that generates an array of evenly spaced values within a specified range

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
a.shape
(3, 5)
a.ndim
2
a.dtype.name
'int64'
a.itemsize
8
a.size
15
type(a)
<class 'numpy.ndarray'>
b = np.array([6, 7, 8])
b
array([6, 7, 8])
type(b)
<class 'numpy.ndarray'>

The type of the array can also be explicitly specified at creation time:

In [1]:
import np as np
c = np.array([[1, 2], [3, 4]], dtype=complex)
c
array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

NameError: name 'np' is not defined

In [ ]:
np.zeros((3, 4))
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
np.ones((2, 3, 4), dtype=np.int16) # 2 means 2-D
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)
np.empty((2, 3))
array([[3.73603959e-262, 6.02658058e-154, 6.55490914e-260],  # may vary
       [5.30498948e-313, 3.14673309e-307, 1.00000000e+000]])

**np.linspace()** generates evenly spaced values over a specified range, which is useful for evaluating functions or creating grids of points.

In [ ]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product
array([[2, 0],
       [0, 4]])
A @ B     # matrix product
array([[5, 4],
       [3, 4]])
A.dot(B)  # another matrix product
array([[5, 4],
       [3, 4]])

In [ ]:
b = np.arange(12).reshape(3, 4)
b
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

b.sum(axis=0)     # sum of each column
array([12, 15, 18, 21])

b.min(axis=1)     # min of each row
array([0, 4, 8])

b.cumsum(axis=1)  # cumulative sum along each row
array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [ ]:
a = np.arange(10)**3
a
array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
a[2]
8
a[2:5]
array([ 8, 27, 64])
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a
array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])
a[::-1]  # reversed a
array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])
for i in a:
    print(i**(1 / 3.))

9.999999999999998  # may vary
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998

Iterating over multidimensional arrays is done with respect to the first axis:

In [ ]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]

However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [ ]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43

In [ ]:
a.ravel()  # returns the array, flattened
array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])
a.reshape(6, 2)  # returns the array with a modified shape
array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])
a.T  # returns the array, transposed
array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])
a.T.shape
(4, 3)
a.shape
(3, 4)

In [ ]:
a = np.floor(10 * rg.random((2, 2)))
a
array([[9., 7.],
       [5., 2.]])
b = np.floor(10 * rg.random((2, 2)))
b
array([[1., 9.],
       [5., 1.]])
np.vstack((a, b))
array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])
np.hstack((a, b))
array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [ ]:
a = np.floor(10 * rg.random((2, 12)))
a
array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])
# Split `a` into 3
np.hsplit(a, 3)
[array([[6., 7., 6., 9.],
       [8., 5., 5., 7.]]), array([[0., 5., 4., 0.],
       [1., 8., 6., 7.]]), array([[6., 8., 5., 2.],
       [1., 8., 1., 0.]])]
# Split `a` after the third and the fourth column
np.hsplit(a, (3, 4))
[array([[6., 7., 6.],
       [8., 5., 5.]]), array([[9.],
       [7.]]), array([[0., 5., 4., 0., 6., 8., 5., 2.],
       [1., 8., 6., 7., 1., 8., 1., 0.]])]

np.hsplit(a, 3) splits the array horizontally (column-wise) into 3 equal parts.
The input array a has 12 columns, so splitting it into 3 parts will result in 3 sub-arrays, each having 4 columns.

np.hsplit(a, (3, 4))
np.hsplit(a, (3, 4)) splits the array a at specific indices: after the 3rd column and after the 4th column.
This creates 3 sub-arrays:
The first sub-array contains the first 3 columns.
The second sub-array contains only the 4th column.
The third sub-array contains the remaining columns from the 5th onward.

In [ ]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

View or shallow copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data

In [ ]:
c = a.view()
c is a
False
c.base is a            # c is a view of the data owned by a
True
c.flags.owndata
False

c = c.reshape((2, 6))  # a's shape doesn't change
a.shape
(3, 4)
c[0, 4] = 1234         # a's data changes
a
array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

**Deep copy (copy() method):** Creates an entirely new array with its own memory allocation. The new array does not share data with the original, meaning changes made to the new array do not affect the original one.

**Difference from views: **In contrast to views, deep copies do not share data with the original array. Views affect the original array when modified because they reference the same data.

In [ ]:
#Deep copy
#The copy method makes a complete copy of the array and its data.

d = a.copy()  # a new array object with new data is created
d is a
False
d.base is a  # d doesn't share anything with a
False
d[0, 0] = 9999
a
array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

Advanced indexing and index tricks
NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

In [ ]:
a = np.arange(12)**2  # the first 12 square numbers
i = np.array([1, 1, 3, 8, 5])  # an array of indices
a[i]  # the elements of `a` at the positions `i`
array([ 1,  1,  9, 64, 25])

j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
a[j]  # the same shape as `j`
array([[ 9, 16],
       [81, 49]])

**np.ix_(a, b, c): **This function generates broadcastable arrays ax, bx, and cx from the original arrays a, b, and c. It turns each 1D array into a multidimensional array that can be broadcasted together to perform operations on all combinations of elements from a, b, and c.

In [ ]:
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])
ax, bx, cx = np.ix_(a, b, c)
ax
array([[[2]],

       [[3]],

       [[4]],

       [[5]]])
bx
array([[[8],
        [5],
        [4]]])
cx
array([[[5, 4, 6, 8, 3]]])
ax.shape, bx.shape, cx.shape
((4, 1, 1), (1, 3, 1), (1, 1, 5))
result = ax + bx * cx
result
array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])
result[3, 2, 4]
17
a[3] + b[2] * c[4]
17

np.random.random(size): Generates random numbers between 0 and 1.

Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes by automatically expanding the smaller array.


arr1 = np.array([1, 2, 3])

arr2 = np.array([4])

arr1 + arr2  # array([5, 6, 7])

np.matmul(arr1, arr2) # Matrix multiplication

np.eye(3)  # 3x3 identity matrix

np.linalg.det(matrix)



np.sort(arr): Returns a sorted array.

np.argsort(arr): Returns the indices that would sort an array.

np.searchsorted(arr, value): Finds indices where elements should be inserted to maintain order.

 Handling Missing Data

np.nan: Represents missing or "not-a-number" data.

np.isnan(arr): Returns a boolean array indicating where nan values are.

np.nanmean(arr): Compute mean ignoring nan values.

arr + 5  # Adds 5 to each element, broadcasting the scalar to the array